general.live_config_reload = true
general.import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[font]
size = 9.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"
