 -- Colorscheme first
require("user.nord")

require("user.autolist")
require("user.autopairs")
-- require("user.cmp")
require("user.comment")
require("user.dap")
require("user.exrc")
require("user.git")
require("user.gitlab")
require("user.go")
require("user.lsp")
require("user.lualine")
require("user.luasnip")
require("user.null-ls")
require("user.surround")
require("user.telescope")
require("user.todo")
require("user.tree")
require("user.treesitter")
require("user.trouble")
